django/kandeArchive/imageview/urls.py
from django.urls import path

from . import views

app_name = 'imageview'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:the_answer>', views.index, name="hello"),
    path('fecate', views.index, name='fecate')
]

django/kandeArchive/kandeArchive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imageview.urls'))
]

django/kandeArchive/imageview/models.py
from django.db import models

# Create your models here.
fs = '/media/swap/archive'

class Album(models.Model):
    name = models.CharField(max_length=200)

    # def __init__(self,directory):
    # directory_parse = directory.split(' ')

class Image(models.Model):

    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    archived = models.BooleanField(default=False)

class Shit(models.Model):
    stuff = models.CharField(max_length=200)
    crap = models.TextField(blank=True, null=True)
    dick = models.BooleanField(default=True)

    def __str__(self):
        return self.stuff

django/kandeArchive/imageview/views.py
from django.shortcuts import render
from django.http import Http404

from .models import Shit

# Create your views here.
def index(request):
    shit = Shit.objects.all()

    context = {
        'the_answer' : 42,
        'shit' : shit
    }

    return render(request, 'imageview/index.html', context)

django/kandeArchive/imageview/templates/imageview/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>K &amp; E Imaging - Super Archive 5000</title>
  </head>
  <body>
    <div>{{ the_answer }}</div>
    <div><a href="{% url 'imageview:hello' the_answer %}"> {{ the_answer}} </a> </div>
    <h1> Edit Shit </h2>

    {% for poop in shit %}
    <div>
      <label for="choice{{forloop.counter}}">{{poop.stuff}}
      <form action="{% url 'imageview:fecate' %}" method="post">
      {% csrf_token %}
      <input type="text" value="{{poop.crap}}" />Crap
      <input type="radio" id="choice{{forloop.counter}}" value="{{poop.dick}}" />Dick {{forloop.counter}}
    </div>

    {% endfor %}

  </body>
</html>